---
# archive.yml
- hosts: all
  remote_user: vagrant
  sudo: yes

  tasks:
  - include: before_install.yml
#  - name: get travis variables 
#    include_vars: travis.yml
#  - name: single before script command
#    shell: "{{before_install[0]}}"
#  - name: all before script commands
#    shell: "{{item}}"
#    with_items: before_install
  #- name: setup
  #  command: = {before_install}

  #- name: placeholder bar
  #  command: /bin/bar
