- name: Clone https://github.com/petere/plxslt.git repo
  git: repo=https://github.com/petere/plxslt.git dest=/home/vagrant/plxslt
- name: Setup plxslt
  shell:  make chdir=/home/vagrant/plxslt
- name: Install plxslt
  shell: make install chdir=/home/vagrant/plxslt 

