- name: update apt-get
  apt: update_cache=yes
- name:  Install packages
  apt: name={{item}} state=present
  with_items:
     - pkg-config
     - git
     - libxml2-dev
     - libxslt-dev 
     - python-pip
     - python-dev
     - postgresql-contrib-9.3
     - postgresql-plpython-9.3
     - postgresql-server-dev-9.3
     - memcached
- name: Update all packages to the latest version
  apt: upgrade=dist
- name: remove requests from pip #authoring resolves intercept error when running tests
  shell: pip uninstall -y requests
- name: install requests from apt-get # this can prob be removed 
  apt: name=python-requests state=present

