#- name: Install virtualenv
#  pip: name=virtualenv

- name: upgrade pip
  pip: name=pip extra_args='-U'
- name: upgrade requests 
  pip: name=requests extra_args='-U'
- name: Clone https://github.com/petere/plxslt.git repo
  git: repo=https://github.com/petere/plxslt.git dest={{deploy_dir}}/plxslt
- name: Setup plxslt
  shell:  make chdir={{deploy_dir}}/plxslt

- name: Install plxslt
  shell: make install chdir={{deploy_dir}}/plxslt 

- name: create requirements file 
  copy: src=/Users/openstax/workspace/cnx-ansible/vagrant-test/provisioning/ansible/requirements.txt dest={{deploy_dir}}
- name: Install python modules
  pip: requirements=requirements.txt chdir={{deploy_dir}} extra_args='--src {{deploy_dir}}' # virtualenv=/home/vagrant/venv
#  pip: requirements=requirements.txt

#    - include: library/plxslt.yml
#    - include: library/install_modules.yml
#    - include: library/test_modules.yml

