---
- hosts: all
  remote_user: vagrant
#  sudo: yes
  vars:
    modules:
    - { remote: Connexions, repo: cnx-query-grammar, branch: master }
    - { remote: Connexions, repo: cnx-epub, branch: master }
    - { remote: Connexions, repo: rhaptos.cnxmlutils, branch: master }
    - { remote: Connexions, repo: plpydbapi, branch: bug-fixes }
    - { remote: Connexions, repo: cnx-archive, branch: master }
    - { remote: Connexions, repo: cnx-publishing, branch: master }
    - { remote: Connexions, repo: cnx-authoring, branch: master }
    local_dir: /Users/openstax/workspace/cnx-ansible/vagrant-test/provisioning/ansible

  handlers:
    - name: restart memcached
      service: name=memcached state=restarted

  tasks:
     - include: setup.yml
#       become: yes
#       become_method: sudo
     - include: plxslt.yml
#       remote_user: vagrant
#       become: yes
       become_method: su
     - include: python_modules.yml
#    - include: library/install_modules.yml
#    - include: library/test_modules.yml

