# test modules
# change authentication settings.
# Note: these settings are prob. too lax

# set roles
- name: Set up archive postgres roles
  sudo: yes
  sudo_user: postgres
  postgresql_user: db=postgres name={{item}} password={{item}} role_attr_flags=SUPERUSER #login_host=default
  with_items:
    - cnxarchive
    - cnxauthoring
    - accounts
# create db
- name: drop archive
  sudo: yes
  sudo_user: postgres
  shell: dropdb --if-exists cnxarchive
- name: drop archive
  sudo: yes
  sudo_user: postgres
  shell: dropdb --if-exists cnxarchive-testing
- name: Set up archive testing database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=cnxarchive owner=cnxarchive #login_host=default
- name: Set up archive testing database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=cnxarchive-testing owner=cnxarchive #login_host=default
- name: drop authoring
  sudo: yes
  sudo_user: postgres
  shell: dropdb --if-exists cnxauthoring

- name: Set up authoring database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=authoring owner=cnxarchive #login_host=default
- name: drop authoring
  sudo: yes
  sudo_user: postgres
  shell: dropdb --if-exists authoring-test
- name: Set up authoring testing database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=authoring-test owner=cnxauthoring #login_host=default
- name: Set up accounts testing database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=accounts-test owner=accounts #login_host=default

# init db
- name: initialize archive
#  shell: cnx-archive-initdb --with-example-data development.ini chdir=/home/vagrant/cnx-archive
  shell: cnx-archive-initdb --with-example-data cnxarchive/tests/testing.ini chdir={{deploy_dir}}/cnx-archive
#- name: make development script for  authoring
#  shell: cp development.ini.example development.ini chdir=/home/vagrant/cnx-authoring
- name: initialize authoring
  sudo: yes
  sudo_user: postgres
#  shell: cnx-authoring-initialize_db  development.ini chdir=/home/vagrant/cnx-authoring
  shell: cnx-authoring-initialize_db  cnxauthoring/tests/testing.ini chdir={{deploy_dir}}/cnx-authoring



# run tests
- name: run archive tests
  shell: python setup.py test chdir={{deploy_dir}}/cnx-archive
  notify:
     - restart memcached

- name: run authoring tests
  shell: python setup.py test chdir={{deploy_dir}}/cnx-authoring

- name: drop archive
  sudo: yes
  sudo_user: postgres
  shell: dropdb --if-exists cnxarchive-testing
- name: Set up archive testing database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=cnxarchive-testing owner=cnxarchive #login_host=default

# test publishing
#- name: init publish db
#  shell: cnx-publishing-initdb testing.ini chdir=/home/vagrant/cnx-publishing
- name: run publishing tests
  shell: python setup.py test chdir={{deploy_dir}}/cnx-publishing




