- name: Set up archive testing database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=cnxarchive-testing owner=cnxarchive #login_host=default
- name: run publishing tests
  shell: python setup.py test chdir={{deploy_dir}}/cnx-publishing
- name: drop archive
  sudo: yes
  sudo_user: postgres
  shell: dropdb cnxarchive-testing

